version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - felipebaltazar
  - IgorCFG
  - Guirollzing

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
