trigger:
- main


jobs:

  #Build Android
  - job: Job_Android
    displayName: Build Android
    pool:
      vmimage: 'windows-latest'
    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x'


    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          cd "Maui.AzurePipelines/"
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

    - task: Bash@3
      displayName: Build Android App
      inputs:
        targetType: 'inline'
        script: |
          cd "Maui.AzurePipelines/"
          dotnet publish Maui.AzurePipelines.csproj -f net7.0-android -c Release


  #Build IOS
  - job: Job_iOS
    displayName: Build iOS
    dependsOn: []
    pool:
      vmimage: 'macOS-latest'
    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x'

    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          cd "Maui.AzurePipelines/"
          dotnet workload install maui-ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

    - task: Bash@3
      displayName: Build IOS App
      inputs:
        targetType: 'inline'
        script: |
          cd "Maui.AzurePipelines/"
          dotnet publish Maui.AzurePipelines.csproj -f net7.0-ios -c Release -r ios-arm64