trigger:
- main

parameters:
- name: PublishStore
  displayName: Publicar nas lojas
  type: boolean
  default: true

- name: dotnetVersion
  displayName: Versão do .Net
  type: string
  default: 8.x

name: $(Major).$(Minor).$(Rev).$(Build.BuildId)

stages:

 - stage: build_android_ios
   displayName: "Build Android e iOS"
   jobs:
    - job: Job_Android
      displayName: Build Android
      pool:
        vmimage: 'windows-latest'
      steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: ${{ parameters.dotnetVersion }}

      - task: DownloadSecureFile@1
        name: keystore
        displayName: Download keystore 
        inputs:
          secureFile: '$(keystore-filename)'

      - script: |
          echo Downloaded $(keystore.secureFilePath)
          echo Working Directory $(Build.Repository.LocalPath)\Maui.AzurePipelines\$(keystore-filename)
          mv $(keystore.secureFilePath) $(Build.Repository.LocalPath)\Maui.AzurePipelines
        displayName: Movendo Keystore para diretorio de trabalho

      - task: Bash@3
        displayName: Instalando MAUI
        inputs:
          targetType: 'inline'
          script: |
            dotnet nuget locals all --clear 
            cd "Maui.AzurePipelines/"
            dotnet workload restore

      - task: JavaToolInstaller@0
        displayName: Instalando JDK
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: CmdLine@2
        displayName: 'Compilando Android App'
        inputs:
          script: |
            cd "Maui.AzurePipelines/"
            dotnet publish Maui.AzurePipelines.csproj -f net8.0-android -c Release /p:ApplicationDisplayVersion=$(Major).$(Minor).$(Rev) /p:ApplicationVersion=$(Build.BuildId) /p:AndroidSigningKeyPass=$(keystore-password) /p:AndroidSigningStorePass=$(keystore-password) /p:AndroidSigningKeyAlias=$(keystore-alias)

      - task: CopyFiles@2
        displayName: Copiando para o diretorio de artifacts
        inputs:
          Contents: |
            **/*.aab
            **/*.apk
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        displayName: Liberando nos artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop_android'
          publishLocation: 'Container'

      - task: ado-discord-webhook@2
        displayName: 'Notificação no discord para falha de build'
        condition: failed()
        continueOnError: true
        inputs:
          webhookId: '$(discord_webhookId)'
          webhookKey: '$(discord_webhookKey)'
          content: '<@&$(discord_mentionRoleId)>'
          embeds: |
            [
              {
                "type": "rich",
                "title": "$(Build.DefinitionName) ($(Build.BuildNumber))",
                "description": "Build android failed!",
                "color": 0xff0000,
                "fields": [
                  {
                    "name": "Build.RequestedFor",
                    "value": "$(Build.RequestedFor)",
                    "inline": true
                  },
                  {
                    "name": "Build.Reason",
                    "value": "$(Build.Reason)",
                    "inline": true
                  }
                ],
                "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
              }
            ]

    - job: Job_iOS
      displayName: Build iOS
      dependsOn: []
      pool:
        #vmimage: 'macOS-latest'
        vmImage: macOS-15
        demands:
        - MSBuild
      steps:
      
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version:  ${{ parameters.dotnetVersion }}

      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: 'Certificados.p12'
          certPwd: $(apple_cert_pass)
          keychain: 'temp'

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provisioningProfileLocation: 'secureFiles'
          provProfileSecureFile: 'Apple_Distribution_Devops_Approval.mobileprovision'

      - task: Bash@3
        displayName: Install MAUI
        inputs:
          targetType: 'inline'
          script: |
            dotnet nuget locals all --clear 
            cd "Maui.AzurePipelines/"
            dotnet workload restore

      - task: Bash@3
        displayName: Build IOS App
        inputs:
          targetType: 'inline'
          script: |
            cd "Maui.AzurePipelines/"
            dotnet publish Maui.AzurePipelines.csproj -f net8.0-ios -c Release /p:ApplicationDisplayVersion=$(Major).$(Minor).$(Rev) /p:ApplicationVersion=$(Build.BuildId)

      - task: CopyFiles@2
        inputs:
          Contents: |
            **/*.app
            **/*.ipa
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop_ios'
          publishLocation: 'Container'

      - task: ado-discord-webhook@2
        displayName: 'Notificação no discord para falha de build'
        condition: failed()
        continueOnError: true
        inputs:
          webhookId: '$(discord_webhookId)'
          webhookKey: '$(discord_webhookKey)'
          content: '<@&$(discord_mentionRoleId)>'
          embeds: |
            [
              {
                "type": "rich",
                "title": "$(Build.DefinitionName) ($(Build.BuildNumber))",
                "description": "Build ios failed!",
                "color": 0xff0000,
                "fields": [
                  {
                    "name": "Build.RequestedFor",
                    "value": "$(Build.RequestedFor)",
                    "inline": true
                  },
                  {
                    "name": "Build.Reason",
                    "value": "$(Build.Reason)",
                    "inline": true
                  }
                ],
                "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
              }
            ]

 - stage: unit_test
   displayName: "Testes de unidade"
   dependsOn: []
   jobs:
    - job: tags
      displayName: Tag build
      pool:
        vmimage: 'windows-latest'
      steps:
      - checkout: none

      - task: Bash@3
        displayName: Preparing tags
        inputs: 
          targetType: 'inline'
          script: |

            Repo=$(echo 'repo-$(Build.Repository.Name)' | tr '[:upper:]' '[:lower:]' | sed -r 's/[ :_.]+/-/g')
            echo "##vso[task.setvariable variable=repo]${Repo}"

            Pipe=$(echo 'pipe-$(Build.DefinitionName)' | tr '[:upper:]' '[:lower:]' | sed -r 's/[ :_.]+/-/g')
            echo "##vso[task.setvariable variable=pipe]${Pipe}"

            echo "##vso[build.addbuildtag]${Pipe}"
            echo "##vso[build.addbuildtag]${Repo}"

      - task: ado-discord-webhook@2
        displayName: 'Notificação no discord para falha de build'
        condition: failed()
        continueOnError: true
        inputs:
          webhookId: '$(discord_webhookId)'
          webhookKey: '$(discord_webhookKey)'
          content: '<@&$(discord_mentionRoleId)>'
          embeds: |
            [
              {
                "type": "rich",
                "title": "$(Build.DefinitionName) ($(Build.BuildNumber))",
                "description": "Unit tests failed!",
                "color": 0xff0000,
                "fields": [
                  {
                    "name": "Build.RequestedFor",
                    "value": "$(Build.RequestedFor)",
                    "inline": true
                  },
                  {
                    "name": "Build.Reason",
                    "value": "$(Build.Reason)",
                    "inline": true
                  }
                ],
                "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
              }
            ]

 - ${{ if contains(parameters.PublishStore, 'true') }}:
    - stage: deployStage
      condition: not(eq(variables['Build.Reason'], 'PullRequest'))
      dependsOn:
        - build_android_ios
        - unit_test

      displayName: Deploy Stage
      jobs:
        - deployment: ios
          dependsOn: []
          environment: AzureDevops Mobile - Staging
          displayName: "Publish IOS - TestFlight"
          pool:
            vmImage: "macos-latest"
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: none

                  - task: DownloadBuildArtifacts@1
                    displayName: "Download IPA"
                    inputs:
                      buildType: "current"
                      downloadType: "single"
                      artifactName: "drop_ios"
                      downloadPath: "$(System.ArtifactsDirectory)"

                  - task: AppStoreRelease@1
                    displayName: "Publish to the App Store TestFlight track"
                    inputs:
                      serviceEndpoint: 'FiveHighAppleStore'
                      releaseTrack: 'TestFlight'
                      appIdentifier: 'com.maui.azurepipeline.approval'
                      appType: 'iOS'
                      ipaPath: '$(System.ArtifactsDirectory)/**/*.ipa'
                      shouldSkipWaitingForProcessing: true
                      shouldSkipSubmission: true

                  - task: ado-discord-webhook@2
                    displayName: 'Notificação no discord para deploy com sucesso'
                    condition: succeeded()
                    continueOnError: true
                    inputs:
                      webhookId: '$(discord_webhookId)'
                      webhookKey: '$(discord_webhookKey)'
                      name: 'Azure Devops'
                      avatar: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxANDRAODQ8ODxAODhAPDxAPDQ8PEA8PFRIWFhYSFhUYHSggGB0lGxUTITEiJSkrMTEuFx8zODMsNyguLisBCgoKDg0OGhAQGy0lHSYtNTUvLS0uNS0tNy8vLS83LSstLS0xLS0tLS0tLS0tLS8tLS0tLSstLS0tLS0tLS8uLf/AABEIAMIBAwMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAABgcBBAUDAgj/xABHEAACAQIBBgUPCgYDAQAAAAAAAQIDEQQFEiExQVEGUmFxsgcTFyIyM1RzgZGTobHR0hQVNDVykpSzwdMWI0JTYnSC4fAk/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAEDBAIF/8QAKBEBAAEDAgUDBQEAAAAAAAAAAAECAxEEMRITFCFRMmFxIjNBocGR/9oADAMBAAIRAxEAPwC8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPKviIU1epOEFvnJRXrI5wu4SvC/yKFuvSV5SdmqUXq0bZMr2vWlVk51JSnJ65Tk5Pzs1WtLNcZntCiu9FM4hbvzthvCcP6en7x87YbwnD+np+8p4F/RR5cdRPhcPzthvCcP6en7x87YbwnD+np+8p4Doo8o6ifC4fnbDeE4f09P3j52w3hOH9PT95TwHRR5OonwuOnlKhNqMa9GTepRqwbfkTNspEsfgFlGdfDShUbk6M1GMm7twauk3ttZ+SxTe03Lp4olZbvcU4wk4AMi8AAAAAAAAAAAAAAAAAAAAAAAAAAA5+XMpxweHlWlpa7WEePN6o/rzJm+3bWVbwsyz8sxHaP+TSvGn/AJb5+X2JF9i1zKvZXdr4YcjEV5VZyqVHnTnJyk97Z5gHr4YAA6+TsjOaU6t4p6VFaJNb3uOaqojdMRlyAS6GT6MVZUoeVZz87PKvkmjNdzmPfDR6tRxzYdcuUWBtZQwMqErS0xfcyWp8nIzVLInOzgJ31Nu94j7dPosghO+pt3vEfbp9FlGq+1K2z64TMAHktwAAAAAAAAAAAAAAAAAQnLPVFo0KsqWHovEZjcZT66qULrXmvNblz6PKd0W6q5xTDmquKe8psCueyhLwJfi3+2OyhLwJfi3+2XdJe8fuFfPo8rGBXPZQl4Evxb/bHZQl4Evxb/bHSXvH7g59HlYwK57J8vAl+Lf7Z9UuqXKbzVglp2/K3oW/vZHSXvH7hPPo8utw7y11qn8lpPt6sb1Gv6aT/p55ey+8r89sXiZ1qk6tR506knKT5d3Ns8h4no2bcW6cMlyvinIAC1w38jYZVayztMYLOa37l5/YSg4XBruqu+0Pa/8Ao7pmuz9S6jYABW7eOLw6q05Qe1aHulsZD2rOz1rQ+cm1iHYzTVqW1dcn0mXWZ3hVch4k76m3e8R9un0WQQnfU273iPt0+iyNV9qU2fXCZgA8luAAAAAAAAAAAAAAAAamVpuOFryi7ONCq09zUHZlAx1F+Za+iYj/AF6vQZQaPS0G1TJqd4ZAB6DKAAAdPCUcyN3revk5DVwNHOec9S1crOic1SmAAHKQAAbeSsV1mqpPuX2suZ7fPYlad9K2kJOhk/Ks6KzWs+GxXs48z/QquUZ7w7oqx2ScHOhlqi1pco8jg/0ueVfLtNL+XGU3yrNj7yngq8LOKG7lDFqjTctuqC3yIie2KxU60s6bvuS1JbkjxNFFPDCqqrITvqbd7xH26fRZBCd9TbveI+3T6LKtV9qXdn1wmYAPJbgAAAAAAAAGABkGABkGDIGnlr6JiP8AXq9BlBIvzLX0TEf69XoMoNHp6Dapk1O8MgA3sofVKDlJRW31HydLB0c2N3rl6luEyPenBRSS1I+jAK3TIMHpSp30vV7QMRptq/8A5nybdjyrxWvb7SMmHiDAJGQYAAyYAGSfdTik1QrT2SqqK/4x09IheTMn1cVVVKjHOb1v+mEeNJ7EWvkrARwtCFGGlQWl7ZSelyfO7mPWXIinh/K+xTOctwAHmtgDAAyAAAAAAAAAAAAA8MbQ67RqUr5vXKc4Xte2dFq9vKUXlfJdXBVpUK8bSjpTXczjsnF7UX2cnhFkGllCj1uqrSV3SqJLOpy38q3rb5madNf5U99pU3rXHHbdRoN3LGS6uCrSoV42ktKa0xnHZKL2o0T2YmJjMMExjdtYKjnPOeqPrZ0Txwlutxtu9e09jiUgB6Uqd9L1e0hJSp30vV7TYQMTmkrnKSc7K7NaUru7MSld3ZgmIQAAkADbybk2rip9boQcnteqMFvlLYRMxEZkiMtQk2QeCNXE2qV86jSelK38ya5E+5XK/MSbIHBOjhbVKtq1Zac5rtIP/GP6v1EiMF7V/ij/AFqt2PzU1sn4Clhqap0IKEVu1ye+T1t85sgGKZz3lp2AAQAAAAAAAAAAAAAAAAAAA5XCLIVLKFHrVVWkrulUS7anLet63rb5mU9jchYiji1g5U3KtJ2pqOlVVsnF7tenZZ3tYvYxm6b7TRZ1NVrtvCq5ZivuhOD4Awhg8yU//ql27qJvralbvaXF5de3kIdi8LOhUlSqxcZwdmn7VvXKXQRHhwqFVRha9eNrSi7ZkeLLffd5ee2xqK5rxV3yru2qYpzCB0qd9L1e02TLjbQ9Fj4nJJXN+7MTlZaTWlK7uxKV3dmCYQAAkAeWIxEaavJ8y2vmOPi8bKpo7mO5bedkxEyiZSHIcqeJx1DDO7jVqOM3F2slFy0PyFxYPB06EFTowjCC1KK9be18rKQ4CfW2E8bL8uZex52u7VRHs16baZAAYWkAAAAAAAAAAAAAAAAAAAAAYnJRTb0JJtvckafzrQ/uw85743vVTxc+iyCF1q3Fecq665pT2jWjUipQalF3s1q0aD0Obwe+iw559NnSK6oxMw7icxl54iMnCSpyUZuLUZNXSe+xXWMoTp1JRqp597ybd86/9V9t95ZJz8r5KhioWl2s13E0ruPJyrkLLN3gnvs4uUcUdkGwmS54uWZTSuldyfcxXKzhY7D1KNWVOtFxnB2aftW9cpbuT8FDD01Tpqy1tvXJ72c3hPkWli6LlNxp1KUW41XoUUtLU3xfZrNFGr+vE7KqrH0+6rQfMZqSvFqS3rSmeWJxMaa7Z6diWtnoMr2bOfi8pJaKel8bYubeaWKxkqmjVHir9d5rHcU+XMy+pzcneTbb2s+QDtDvcBPrbCeNl+XMvYongJ9bYTxsvy5l7Hk6/wBcfH9lt0vpn5AAYWkAAAAAAAAAAAAAAAAAAAAAeON71U8XPosgaJ5je9VPFz6LIIatNtKi9+Ev4O/RYc8+mzpHN4PfRYc8+mzpFFz1Stp2gABw6CrOqnlzEdfeBUZUqCjGbfhN0ne/FT0W3rTsLTOTwjyDRyjQdGsrNXdOoks6lPeuTetpdYrporiaoV3aZqpxChKdWUe5lKPM2j5k23dttva9LN/LeR62AryoYiNpLTGS7ipDZOL3ew557sTExmHmzEx2kABIAADvcBPrbCeNl+XMvYongJ9bYTxsvy5l7Hk6/wBcfH9lt0vpn5AAYWkAAAAAAAAAAAAAAAAAAAAAeON71U8XPosgZP6sFKLi9Uk07a7NWOV/DlHjVfvR+Evs3IozlVcomrZGYVpxVlOaW5SaRn5RU49T78veSX+HKPGq/ej8I/hyjxqv3o/CXc+hxy6ka+U1P7lT78vedvgvUlKdXOlKVoxteTe17za/hyjxqv3o/CbeT8mQw7k4Obzkk85p6uZFdy7RVTMQ6poqicy3QAZlzk8I8g0co0HRrKzV3TqJdvSnvXJvW0pHLmR62AryoYiNmtMZLuKkNk4vd7D9CHMy9kKhlCkqWJi2ovOhKLzZwf8Ai+XaatNqZtTidlN2zFfeN35+BcPYzwHGxPpY/COxngONifSx+E3dda92bpq1PAuHsZ4DjYn0sfhMdjPAcbE+lj8I6617nTVoD1PaEqmVsNmq+Y51JviwVOSu/K4ryovI5WQuD2GyfFxw1PNc7Z85NyqTtqvJ7ORaDqnn6m9F2vMbNVm3wU4kABnWgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//Z'
                      embeds: |
                        [   
                          {   
                            "type": "rich",   
                            "title": "$(Build.DefinitionName) ($(Build.BuildNumber))",   
                            "description": "Versão $(Major).$(Minor).$(Rev).$(Build.BuildId) IOS disponível no TestFlight!",
                            "color": 0x008000,   
                            "fields": [   
                              {   
                                "name": "Build.RequestedFor",   
                                "value": "$(Build.RequestedFor)",   
                                "inline": true   
                              },   
                              {   
                                "name": "Build.Reason",
                                "value": "$(Build.Reason)",
                                "inline": true
                              }   
                            ],   
                            "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
                          }   
                        ]

                  - task: ado-discord-webhook@2
                    displayName: 'Notificação no discord para falha de deploy'
                    condition: failed()
                    continueOnError: true
                    inputs:
                      webhookId: '$(discord_webhookId)'
                      webhookKey: '$(discord_webhookKey)'
                      content: '<@&$(discord_mentionRoleId)>'
                      embeds: |
                        [
                          {
                            "type": "rich",
                            "title": "$(Build.DefinitionName) ($(Build.BuildNumber))",
                            "description": "Deploy IOS failed!",
                            "color": 0xff0000,
                            "fields": [
                              {
                                "name": "Build.RequestedFor",
                                "value": "$(Build.RequestedFor)",
                                "inline": true
                              },
                              {
                                "name": "Build.Reason",
                                "value": "$(Build.Reason)",
                                "inline": true
                              }
                            ],
                            "url": "$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs"
                          }
                        ]

        - deployment: android
          dependsOn: []
          environment: AzureDevops Mobile - Staging
          displayName: "Publish Android - teste interno"
          pool:
            vmimage: 'windows-latest'
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: none

                  - task: DownloadBuildArtifacts@1
                    displayName: "Download "
                    inputs:
                      buildType: "current"
                      downloadType: "single"
                      artifactName: "drop_android"
                      downloadPath: "$(System.ArtifactsDirectory)"

                  - task: GooglePlayRelease@4
                    displayName: Publicando no teste interno
                    inputs:
                      serviceConnection: 'FiveHighGooglePlay'
                      applicationId: 'com.maui.azurepipeline.approval'
                      action: 'SingleBundle'
                      bundleFile: '$(System.ArtifactsDirectory)/**/*.aab'
                      track: 'internal'